"""init_db

Revision ID: fef009c2403a
Revises: 10625595b3c2
Create Date: 2024-06-29 11:18:46.842930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef009c2403a'
down_revision: Union[str, None] = '10625595b3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atletas', 'cpf',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atletas', 'cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    # ### end Alembic commands ###
